services:
  web:
    build: .
    container_name: django_app
    env_file:
      - .env
    volumes:
      - static_volume:/pc_components_shop/static
      - media_volume:/pc_components_shop/media/
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/pc_components_shop/static
      - media_volume:/pc_components_shop/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
  static_volume:
  media_volume:
