# Generated by Django 5.2.1 on 2025-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="Київ", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="0000000000", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="warehouse",
            field=models.CharField(default="default warehouse", max_length=100),
            preserve_default=False,
        ),
    ]
