# Generated by Django 5.2.1 on 2025-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_address_order_city_order_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="purchased_items",
            field=models.TextField(default=""),
        ),
    ]
