# Generated by Django 5.2.1 on 2025-12-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_options_order_notes_order_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="basket_history",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="order",
            name="purchased_items",
            field=models.TextField(blank=True, default=""),
        ),
    ]
