# Generated by Django 5.2.1 on 2025-06-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
