# Generated by Django 5.2.1 on 2025-06-30 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="wished_by",
            field=models.ManyToManyField(
                blank=True, related_name="wishlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
